chore: upgrade deps
WTTJ/wttj-config-front pull request #16
Opened 2022-03-10 13:37 UTC by mleralec

I also move all deps (eslint/prettier) from **peerDependencies** to **dependencies** to prevent installing all packages in each project who use wttj-config-front

2022-03-10 13:41 UTC, theo-mesnil approved these changes

2022-03-10 13:45 UTC, guillaumewttj approved these changes

2022-03-10 13:49 UTC, guillaumewttj requested changes
Manque le changement babel-eslint vers @babel/eslint-parser dans la config eslint

2022-03-10 14:42 UTC, mleralec commented
@guillaumewttj bien vu 👀

2022-03-10 14:43 UTC, guillaumewttj approved these changes

2022-03-24 13:14 UTC, closed without merging

2022-03-24 13:20 UTC, cnairiwttj approved these changes